# values for PRODUCTION environment

image:
  name: "registry.example.com/k8s-haproxy-external-lb"

# inventory - Ansible inventory file
inventory: |
  [inhosts]
  delta.pipebreaker.pl    haproxy_bind=ipv6@:443
  epsilon.pipebreaker.pl  haproxy_bind=ipv6@:443
  taugw-legacy.pipebreaker.pl haproxy_bind=ipv4@:443 haproxy_bind_insecure=ipv4@:80 ansible_user=opc ansible_become_method=sudo ansible_become=true
