---
- name: Configure HAProxy loadbalancer for k8s tau cluster
  hosts: inhosts

  tasks:
  - name: Install HAProxy package
    ansible.builtin.package:
      name: haproxy
      state: present

  - name: Get Traefik endpoints
    kubernetes.core.k8s_info:
      kind: endpoints
      namespace: kube-system
      name: traefik
    register: traefik_endpoints
    delegate_to: localhost

  - name: Extract addresses
    set_fact:
      traefik_addresses: >-
        {{
          traefik_endpoints.resources[0].subsets[0].addresses
        }}

  - name: Extract web port
    set_fact:
      traefik_insecure_port: >-
        {{
          traefik_endpoints.resources[0].subsets[0].ports
          | selectattr('name', 'equalto', 'web')
          | map(attribute='port')
          | first
        }}

  - name: Extract websecure port
    # here I want 'websecure' or 'websecure-http3'
    set_fact:
      traefik_websecure_port: >-
        {{
          traefik_endpoints.resources[0].subsets[0].ports
          | selectattr('name', 'match', '^websecure')
          | map(attribute='port')
          | first
        }}

  - name: Generate HAProxy config
    ansible.builtin.template:
      src: "haproxy.cfg.j2"
      dest: "/etc/haproxy/haproxy.cfg"
    vars:
      ep_addresses:   "{{ traefik_addresses }}"
      insecure_port:  "{{ traefik_insecure_port }}"
      websecure_port: "{{ traefik_websecure_port }}"
    notify:
      - restore selinux context
      - restart haproxy

  handlers:
    - name: restore selinux context
      shell: restorecon -v /etc/haproxy/haproxy.cfg

    - name: restart haproxy
      ansible.builtin.service:
        name: haproxy
        state: restarted
